DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS post;

CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE deeds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userid INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  address TEXT,
  location TEXT NOT NULL,
  isdone BOOLEAN NOT NULL,
  date NUMERIC

  FOREIGN KEY (userid) REFERENCES users(id)
);

CREATE TABLE eventreg(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userid INTEGER NOT NULL,
  eventid INTEGER NOT NULL,
  likes INTEGER DEFAULT 0,
  dislikes INTEGER DEFAULT 0,

  FOREIGN KEY (userid) REFERENCES users(id),
  FOREIGN KEY (eventid) REFERENCES deeds(id)
)